version: '3.8'

# Development docker-compose file that builds from source
# Usage: docker-compose -f docker-compose.dev.yml up --build

services:
  youtube-study-buddy:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - fluidnotions/youtube-study-buddy:latest
        - fluidnotions/youtube-study-buddy:dev
    container_name: youtube-study-buddy-dev
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - TOR_HOST=tor-proxy
      - TOR_PORT=9050
      # RAG Configuration
      - RAG_ENABLED=${RAG_ENABLED:-true}
      - RAG_MODEL=${RAG_MODEL:-all-mpnet-base-v2}
      - RAG_SIMILARITY_THRESHOLD=${RAG_SIMILARITY_THRESHOLD:-0.3}
      - RAG_MAX_RESULTS=${RAG_MAX_RESULTS:-5}
      - RAG_BATCH_SIZE=${RAG_BATCH_SIZE:-32}
      - CHROMA_PERSIST_DIR=/app/.chroma_db
      - MODEL_CACHE_DIR=/app/.cache
      # Development Debug Settings
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
    volumes:
      - ./notes:/app/notes
      - ./src:/app/src  # Mount source for live development
      - ./streamlit_app.py:/app/streamlit_app.py  # Mount streamlit app
      - tracker-data-dev:/app/tracker  # Persistent exit node tracker
      - chroma_data_dev:/app/.chroma_db  # RAG vector database
      - model_cache_dev:/app/.cache  # Sentence transformer models
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    depends_on:
      tor-proxy:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G

  tor-proxy:
    image: osminogin/tor-simple:latest
    container_name: ytstudybuddy-tor-proxy-dev
    restart: unless-stopped
    environment:
      - LOCATION=US
    volumes:
      - tor-data-dev:/var/lib/tor
    healthcheck:
      test: ["CMD", "curl", "-x", "socks5://localhost:9050", "https://check.torproject.org", "-s", "-o", "/dev/null", "-w", "%{http_code}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  tor-data-dev:
    driver: local
  tracker-data-dev:
    driver: local  # Persistent exit node tracker data
  chroma_data_dev:
    driver: local  # RAG vector database storage (dev)
  model_cache_dev:
    driver: local  # Sentence transformer models cache (dev)
