version: '3.8'

services:
  youtube-study-buddy:
    build: .
    # Or use: image: fluidnotions/youtube-study-buddy:latest
    container_name: youtube-study-buddy
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./notes:/app/notes
    restart: unless-stopped
    # Note: Tor is now installed inside the container, no separate service needed