version: '3.8'

services:
  youtube-study-buddy:
    image: fluidnotions/youtube-study-buddy:latest
    container_name: youtube-study-buddy
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - TOR_HOST=tor-proxy
      - TOR_PORT=9050
      # RAG Configuration
      - RAG_ENABLED=${RAG_ENABLED:-true}
      - RAG_MODEL=${RAG_MODEL:-all-mpnet-base-v2}
      - RAG_SIMILARITY_THRESHOLD=${RAG_SIMILARITY_THRESHOLD:-0.3}
      - RAG_MAX_RESULTS=${RAG_MAX_RESULTS:-5}
      - RAG_BATCH_SIZE=${RAG_BATCH_SIZE:-32}
      - CHROMA_PERSIST_DIR=/app/.chroma_db
      - MODEL_CACHE_DIR=/app/.cache
    volumes:
      - ./notes:/app/notes
      - tracker-data:/app/tracker
      - chroma_data:/app/.chroma_db
      - model_cache:/app/.cache
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    depends_on:
      tor-proxy:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G

  tor-proxy:
    image: osminogin/tor-simple:latest
    container_name: ytstudybuddy-tor-proxy
    restart: unless-stopped
    # Ports exposed only internally to youtube-study-buddy container
    # No need to expose to host since app connects via docker network
    # ports:
    #   - "8118:8118"  # HTTP proxy (Privoxy)
    #   - "9050:9050"  # SOCKS5 proxy (Tor)
    environment:
      - LOCATION=US          # Prefer US exit nodes
      # - TORUSER=torrr      # Optional: HTTP proxy auth
      # - PASSWORD=secret    # Optional: HTTP proxy auth password
    volumes:
      - tor-data:/var/lib/tor
    healthcheck:
      test: ["CMD", "curl", "-x", "socks5://localhost:9050", "https://check.torproject.org", "-s", "-o", "/dev/null", "-w", "%{http_code}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  tor-data:
    driver: local
  tracker-data:
    driver: local  # Persistent exit node tracker data
  chroma_data:
    driver: local  # RAG vector database storage
  model_cache:
    driver: local  # Sentence transformer models cache

# Two container setup:
# - tor-proxy: Dedicated Tor proxy (dperson/torproxy)
# - youtube-study-buddy: App container connects to tor-proxy
#
# Key difference from single container:
# - Tor runs in separate network context (different docker network)
# - May help avoid some YouTube blocking (separate IP context)
# - dperson/torproxy has proven configuration
#
# Volumes:
# - ./notes: Study notes output (bind mount to host)
# - tracker-data: Exit node tracker persistence (named volume)
# - tor-data: Tor configuration and state (named volume)
